### PR TITLE
Fixes for Python 3

### PR DESCRIPTION
**Pull request by davedoesdev**
Tests pass on 2 and 3 locally. Travis is a WIP...

### CODE REVIEW

**Comment by davedoesdev** [comment]
OK this is good to go now - tests pass on Python 2.7 and 3.6

**Comment by jayvdb** [comment]
This patch, and an extra one for py37 support, worked for me at https://build.opensuse.org/package/show/home:jayvdb:django/python-pyVows

**Comment by marcelometal** [comment]
Thank you @davedoesdev

**Comment by davedoesdev** [comment]
@marcelometal no problem, thanks for merging.
Feel free to take anything from 

https://github.com/heynemann/pyvows/compare/master...davedoesdev:master

that you think is needed.

**Pull request merged**
